name: Run Unit Tests on PR

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Create empty .env
        run: echo "" > .env
      - name: Run tests
        run: npm run test
